"""add file_extension field-1

Revision ID: 14b56059aa5b
Revises: 7427ab56175c
Create Date: 2024-05-28 19:49:44.425639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b56059aa5b'
down_revision: Union[str, None] = '7427ab56175c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_extension', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_extension')
    # ### end Alembic commands ###
