"""count field-2

Revision ID: 3ca9e038ecf6
Revises: 7a49b0e9fd31
Create Date: 2024-05-26 10:19:31.157110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca9e038ecf6'
down_revision: Union[str, None] = '7a49b0e9fd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
