"""Delete count-1

Revision ID: 7427ab56175c
Revises: 3ca9e038ecf6
Create Date: 2024-05-28 19:16:13.977209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7427ab56175c'
down_revision: Union[str, None] = '3ca9e038ecf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
