"""count field-1

Revision ID: 7a49b0e9fd31
Revises: 9668fe8d5656
Create Date: 2024-05-26 10:06:58.743136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a49b0e9fd31'
down_revision: Union[str, None] = '9668fe8d5656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'count')
    # ### end Alembic commands ###
