"""file drop owner_id-1

Revision ID: 87401a664837
Revises: a80e8f5dfac1
Create Date: 2024-05-11 13:10:44.876677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87401a664837'
down_revision: Union[str, None] = 'a80e8f5dfac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_owner_id', table_name='file')
    op.drop_constraint('file_owner_id_fkey', 'file', type_='foreignkey')
    op.drop_column('file', 'owner_id')
    op.drop_column('user', 'jopa')
    op.drop_column('user', 'is_piska')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_piska', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('jopa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('file_owner_id_fkey', 'file', 'user', ['owner_id'], ['id'])
    op.create_index('ix_file_owner_id', 'file', ['owner_id'], unique=False)
    # ### end Alembic commands ###
