"""UUID field-1

Revision ID: 9668fe8d5656
Revises: 43bf11cc24e0
Create Date: 2024-05-26 09:39:26.693909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9668fe8d5656'
down_revision: Union[str, None] = '43bf11cc24e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uuid_', sa.String(), nullable=True))
    op.create_index(op.f('ix_file_uuid_'), 'file', ['uuid_'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uuid_'), table_name='file')
    op.drop_column('file', 'uuid_')
    # ### end Alembic commands ###
