"""add count again-1

Revision ID: acabf7d22cb4
Revises: 14b56059aa5b
Create Date: 2024-05-28 20:38:58.075241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acabf7d22cb4'
down_revision: Union[str, None] = '14b56059aa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_extension',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_extension',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
