"""add download count field-1

Revision ID: d43c65f4b3bf
Revises: ec9d830a75d4
Create Date: 2024-05-29 19:47:39.385976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43c65f4b3bf'
down_revision: Union[str, None] = 'ec9d830a75d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column(
        'download_count', sa.Integer(), nullable=True))
    op.alter_column('file', 'count',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('file', 'file_extension',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_extension',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('file', 'count',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('file', 'download_count')
    # ### end Alembic commands ###
